//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddMath.WordAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddMath.WordAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key,suggestion
        ///v (וקטור),\vec  
        ///vec (וקטור),\vec  
        ///v2 (וקטור 2),[■(@)] 
        ///v3 (וקטור 3),[■(@@)] 
        ///a (α),α
        ///b (β),β
        ///l (λ),λ
        ///. (⋅),⋅
        ///sqrt (√),√
        ///atop (¦),¦
        ///circ (∘),∘
        ///hat (וקטור יחידה ̂x),\hat  
        ///&amp; (וגם ∧),∧
        ///| (או ∨),∨
        ///U (איחוד ∪),∪
        ///^ (חיתוך ∩),∩
        ///F (שדה כלשהו F),\doubleF 
        ///R (ממשיים ℝ),ℝ
        ///R+ (ממשיים ℝ),ℝ^+ 
        ///N (טבעיים ℕ),ℕ
        ///Z (שלמים Z),\doubleZ 
        ///above (\above),┴
        ///&quot;xyz (וקטור x,y,z)&quot;,[■(x@y@z)] 
        ///dot ( ̇ ),\dot  
        ///ddot ( ̈ ),\ddot  
        ///matrix (מטריצה ריקה),■(
        ///&quot;propto (פרופוציאונלי ל, ∝)&quot;,∝
        ///forall (∀ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1037\ansi\ansicpg1255\uc1\adeff42\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs1037{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f42\fbidi \fswiss\fcharset0\fprq2{\*\panose 00000000000000000000}FrankRuehl;}{\f44 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VBA {
            get {
                return ResourceManager.GetString("VBA", resourceCulture);
            }
        }
    }
}
